# Generated by Django 5.2.5 on 2025-10-14 10:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gasapp', '0002_usertable_agencytable_notification_gasdetails_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='usertable',
            name='LOGINID',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='gasapp.logintable'),
        ),
    ]
