# Generated by Django 5.2.5 on 2025-10-17 05:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gasapp', '0003_usertable_loginid'),
    ]

    operations = [
        migrations.RenameField(
            model_name='gasdetails',
            old_name='gasid',
            new_name='event',
        ),
        migrations.RenameField(
            model_name='gasdetails',
            old_name='quantity',
            new_name='gas_value',
        ),
        migrations.RemoveField(
            model_name='gasdetails',
            name='USER',
        ),
        migrations.AddField(
            model_name='gasdetails',
            name='device_id',
            field=models.IntegerField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='gasdetails',
            name='timestamp',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='usertable',
            name='device_id',
            field=models.IntegerField(blank=True, max_length=100, null=True),
        ),
    ]
