# Generated by Django 5.2.5 on 2025-10-17 05:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gasapp', '0004_rename_gasid_gasdetails_event_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gasdetails',
            name='timestamp',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
