# Generated by Django 5.2.5 on 2025-10-17 06:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gasapp', '0005_alter_gasdetails_timestamp'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='notification',
            name='USERID',
        ),
        migrations.AddField(
            model_name='notification',
            name='deviceid',
            field=models.IntegerField(blank=True, max_length=100, null=True),
        ),
    ]
