# Generated by Django 5.2.5 on 2025-10-17 10:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gasapp', '0006_remove_notification_userid_notification_deviceid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='complainttable',
            name='date',
            field=models.DateField(auto_now_add=True, null=True),
        ),
        migrations.AlterField(
            model_name='complainttable',
            name='replay',
            field=models.CharField(blank=True, default='pending', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='gasdetails',
            name='device_id',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='notification',
            name='deviceid',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='usertable',
            name='device_id',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
