# Generated by Django 5.2.5 on 2025-10-17 11:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gasapp', '0007_alter_complainttable_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='gasdetails',
            name='fan',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='gasdetails',
            name='light',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='gasdetails',
            name='shutter',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
