# Generated by Django 5.2.5 on 2025-10-18 11:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gasapp', '0008_gasdetails_fan_gasdetails_light_gasdetails_shutter'),
    ]

    operations = [
        migrations.RenameField(
            model_name='gasdetails',
            old_name='fan',
            new_name='fan_status',
        ),
        migrations.RenameField(
            model_name='gasdetails',
            old_name='light',
            new_name='light_status',
        ),
        migrations.RenameField(
            model_name='gasdetails',
            old_name='shutter',
            new_name='servo_position',
        ),
    ]
