# Generated by Django 5.2.5 on 2025-10-21 11:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gasapp', '0009_rename_fan_gasdetails_fan_status_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='fireandsafety',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Phone', models.IntegerField(blank=True, null=True)),
                ('place', models.CharField(blank=True, null=True)),
                ('LOGINID', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='gasapp.logintable')),
            ],
        ),
    ]
