# Generated by Django 5.2.5 on 2025-10-22 05:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gasapp', '0010_fireandsafety'),
    ]

    operations = [
        migrations.DeleteModel(
            name='FeedbackTable',
        ),
    ]
