# Generated by Django 5.2.5 on 2025-10-22 10:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gasapp', '0012_notification_viewed'),
    ]

    operations = [
        migrations.CreateModel(
            name='notificationbysafety',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.CharField(blank=True, max_length=100, null=True)),
                ('date', models.DateTimeField(auto_now=True, null=True)),
                ('consumernumber', models.CharField(blank=True, max_length=100, null=True)),
            ],
        ),
    ]
