# Generated by Django 5.2.7 on 2025-10-24 09:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gasapp', '0013_notificationbysafety'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gasdetails',
            name='timestamp',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
