# Generated by Django 5.2.7 on 2025-10-24 09:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gasapp', '0014_alter_gasdetails_timestamp'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gasdetails',
            name='device_id',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='gasdetails',
            name='fan_status',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='gasdetails',
            name='light_status',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='gasdetails',
            name='timestamp',
            field=models.DateTimeField(auto_now_add=True, default='2025-10-24 15:22:01'),
            preserve_default=False,
        ),
    ]
