# Generated by Django 5.2.7 on 2025-10-24 10:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gasapp', '0015_alter_gasdetails_device_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gasdetails',
            name='fan_status',
            field=models.CharField(blank=True, default=0, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='gasdetails',
            name='light_status',
            field=models.CharField(blank=True, default=0, max_length=100, null=True),
        ),
    ]
